on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install all dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Archive production artifacts for ${{ matrix.os }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            packages/main/dist/*.exe
            packages/main/dist/*.dmg
            packages/main/dist/*.AppImage

  publish:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download production build artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: List all files and folders
        run: ls artifacts

      - name: Create Release and upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/**/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
